version: "3"

services:
  golf:
    image: mariadb:latest
    restart: unless-stopped
    container_name: golf
    volumes:
      - ./RDBMS/MariaDB:/var/lib/mysql
    ports:
      - 13309:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test
networks:
  service:
    driver: bridge
volumes:
  sqlserver_data:
