CREATE DATABASE golf;

CREATE USER 'dev'@'%' IDENTIFIED BY 'dev1234';
-- GRANT ALL PRIVILEGES ON golf.* TO 'dev'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP ON golf.* TO 'dev'@'%';

FLUSH PRIVILEGES;
SHOW GRANTS FOR 'dev'@'%';
